development:
  adapter: postgresql
  encoding: unicode
  database: google_development
  pool: 5
  host: localhost
  username: postgres
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: google_production 
  pool: 5
  host: localhost
  username: postgres
  password: 1234